GRANT ALL ON *.* TO 'dd_user'@'%'; FLUSH PRIVILEGES;

CREATE DATABASE IF NOT EXISTS `dd_dev` DEFAULT CHARACTER SET `utf8` COLLATE 'utf8_general_ci';
CREATE DATABASE IF NOT EXISTS `dd_test` DEFAULT CHARACTER SET `utf8` COLLATE 'utf8_general_ci';
