version: '3'
services:
  mysql:
    image: mysql:5.7.21
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - mysql-data:/var/lib/mysql
      # Script to execute when our container is started for the first time
      - ./docker/initdb.d:/docker-entrypoint-initdb.d
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_general_ci']
  redis:
    image: redis:4-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c 'bundle exec sidekiq -e ${RACK_ENV:-development} -r ./config/application.rb -C ./config/sidekiq.yml'
    volumes:
      - .:/usr/src/app/
    stdin_open: true
    tty: true
    env_file:
      - .env
    depends_on:
      - redis
      - mysql
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c 'bundle exec puma -e ${RACK_ENV:-development}'
    volumes:
      - .:/usr/src/app/
    stdin_open: true
    tty: true
    ports:
      - "3001:9292"
    env_file:
      - .env
    depends_on:
      - redis
      - mysql
volumes:
  redis-data:
    driver: local
  mysql-data:
    driver: local
